version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 10000000pedro
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000000pedro
      - 10000token
      - 100000000stake
  - name: digo
  - name: pedro
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 10000000pedro
    - 5token
    - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
  - name: validator1
    bonded: 100000000stake
  - name: validator2
    bonded: 200000000stake
  - name: validator3
    bonded: 300000000stake
