#!/usr/bin/env bash

# Ex.: transfer-ticket c369e813cff666d346b668174f7fdcef02b6a0d6e4324864b752ed3233e50083 alice bob

chainvited tx ticket transfer-ticket "$1" "$(chainvited keys show $3 -a)" --from "$(chainvited keys show $2 -a)" --gas auto
